version: '3.8'
services:
  app:
    container_name: max-tg-bridge
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    # ports:
    #   - "8000:8000"  # если нужно пробросить порты
    command: uv run app/main.py
