[project]
name = "max-to-telegram"
version = "0.1.0"
description = "Проверяет сообщения в MAX и пересылает в Telegram"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "environs>=14.5.0",
    "httpx>=0.28.1",
]
